set(triple aarch64-linux-gnu)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_ID GNU)

set(CMAKE_AR ${triple}-ar )
set(CMAKE_RANLIB ${triple}-ranlib )
set(CMAKE_ADDR2LINE ${triple}-addr2line)
set(CMAKE_AR ${triple}-ar)
set(CMAKE_CXX_COMPILER_AR ${triple}-gcc-ar)
set(CMAKE_CXX_COMPILER_RANLIB ${triple}-gcc-ranlib)
set(CMAKE_C_COMPILER_AR ${triple}-gcc-ar)
set(CMAKE_C_COMPILER_RANLIB ${triple}-gcc-ranlib)
set(CMAKE_LINKER ${triple}-ld)
set(CMAKE_NM ${triple}-nm)
set(CMAKE_OBJCOPY ${triple}-objcopy)
set(CMAKE_OBJDUMP ${triple}-objdump)
set(CMAKE_RANLIB ${triple}-ranlib)
set(CMAKE_READELF ${triple}-readelf)
set(CMAKE_STRIP ${triple}-strip)

set(CMAKE_TOOLCHAIN_EXTRA_CFLAGS "-static")
