name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23
        add-to-path: false

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-$MINSDKVERSION -DANDROID_ABI=$ABI -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=$MINSDKVERSION
      env:
        NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        ABI: arm64-v8a
        MINSDKVERSION: 23

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
